### ISSUE TITLE
How to downgrade torch version?

### ISSUE THREAD

**Issue by ajay960singh** [pytorch/xla#1348]
Hey guys, I'm trying to train my image classification model on multi-cores. I'm using Pytorch-nightly version but the problem is that torch version is 1.4.0a0+be75795, which isn't compatible with my Torchvision version(0.3.0). It gives the following error-

`AttributeError: module 'torch' has no attribute 'gels'`

This gels attribute is defined in previous torch versions, so how can I downgrade only the torch version to 1.2.0 once I'm inside the container?

Thanks

**Comment by zcain117** [comment]
I was wondering: which torchvision model are you using?

I'm looking more into this but meanwhile one workaround is to build manually. Follow the steps in [this doc](https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md) to clone the source and then I'd recommend "building with script" - but first you would need to create `xla/.torch_commit_id` which is read [here](https://github.com/pytorch/xla/blob/master/scripts/build_torch_wheels.sh#L75) in the script.

**Comment by ajay960singh** [comment]
Thanks for your reply. I'm using my own model so its not provided by torchvision. I get the error while using torchvision.transforms, as shown below-

```
File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision-0.3.0-py3.6-linux-x86_64.egg/torchvision/transforms/functional.py", line 431, in _get_perspective_coeffs
    res = torch.gels(B, A)[0]
```

Okay, I'll try that but after creating `xla/.torch_commit_id` file, do I leave it blank? Also, where do I mention the version of torch that I want?

**Comment by zcain117** [comment]
Ah thanks for the details. In this case, it's probably better to upgrade torchvision version instead of downgrade torch. Our project is currently using 0.3.0 which has the call to `gels()` but I [see that in 0.4.0](https://github.com/pytorch/vision/blob/v0.4.0/torchvision/transforms/functional.py) they've replaced it with `lstsq`.

I'll look into changing our project to use 0.4.0 but meanwhile you could upgrade by building manually after changing [this line](https://github.com/pytorch/xla/blob/master/scripts/build_torch_wheels.sh#L101) instead of the torch commit.

**Comment by zcain117** [comment]
I updated the torchvision version and the change should appear in tomorrow's nightly build
