### ISSUE TITLE
[feature request]Support for sparse tensor

### ISSUE THREAD

**Issue by hxssgaa** [pytorch/xla#1369]
Currently the pytorch_xla has no support for sparse tensors like `torch.sparse.FloatTensor`. I'm not sure whether TPU is capable of doing sparse matrix calculations. It would be nice if we can have sparse matrix calculation capability in the pytorch_xla. Thanks.

David

**Comment by zcain117** [comment]
Thanks for the feedback - I'll bring this up with the team

**Comment by zcain117** [comment]
It sounds like this won't happen for quite a while due to hardware limitations. TPUs don't work well on sparse data, so even if we could support them in pytorch/xla, the performance would probably be quite bad. 

https://cloud.google.com/tpu/docs/tpus mentions that sparse data isn't a good fit for TPUs: `Workloads that access memory in a sparse manner might not be available on TPUs.`

**Comment by hxssgaa** [comment]
Thank you for the update. I will close the issue for now until TPU hardware team supports sparse tensors.
