### ISSUE TITLE
Why does printing progress every step slow things down?

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#1399]
## ❓ Questions and Help

@dlibenzi  You mentioned the ParallelLoader background sender and its ability somehow to overlap communication between TPU and CPU without interrupting the flow of TPU computations.  But, you also mentioned that printing the values of summary statistics (which ultimately requires calling `loss.item()` and so forth) triggers "an exit from the tensor world to CPU world".  I'm wondering why this would be the case?  Couldn't there be some sort of asynchronous process in which the tensor world does the quick `item()` calculation, sends the value to the CPU in the "background" and resumes its cycle, while the CPU goes to work printing the result?

Thanks very much,

Henry

**Comment by dlibenzi** [comment]
Please check https://github.com/pytorch/xla/pull/1380 and its comments.
In order to optimize the reporting when multiple tensors need to be materialized, the new API should be used like:

https://github.com/pytorch/xla/pull/1380/files#diff-52339ab6ddf6bd6097119a40eea424e7R200

You still need to throttle (report once every N steps).

**Comment by hrbigelow** [comment]
Cool, thanks @dlibenzi I will check it out.
