### ISSUE TITLE
Why XLATensorImpl has no at::storage data

### ISSUE THREAD

**Issue by kwgqjj** [pytorch/xla#1431]
## ❓ Questions and Help
hello, 
when i read the xla code about class XLATensorImpl, i am confused with one function of XLATensorImpl, the function is as following:
    const at::Storage& XLATensorImpl::storage() const {
          XLA_ERROR() << "XLA tensors do not have storage";
    }
As i know, the storage of TensorImpl in pytorch is used to save real data, but why XLATensorImpl doesn't have it and how the real data will be transfered from pytorch to xla. I will be very grateful if someone could give me some help.

**Comment by asuhan** [comment]
XLA compiles entire graphs as a single computation unit and doesn't materialize intermediate results when it can avoid it. For example, if we had:

```
tmp = x + y
result = tmp + z
```

the compiler doesn't need to materialize `tmp` to compute `result` (unless the user does something which would force it, like printing `tmp`). The XLA compiler leverages this flexibility to achieve superior performance.

**Comment by kwgqjj** [comment]
hi, asuhan, thanks for your prompt reply for my question. For the intermediate tensor, such as tmp, i could understand it may not need to materialize it. However, for x or y tensor in your sample code, how XLATensorImpl deal with the at::storage data? for example:
   x = torch.ones(1,3,224,224, device=xm.mlu_device())

if XLATensorImpl doesn't materialize at::storage, how the data of tensor x can be passsed from pytorch to xla?

**Comment by asuhan** [comment]
In that case, `x` and `y` become effective parameters of `ComputationClient::ExecuteComputation` after being converted to `XLATensor` - one of the constructors takes an `at::Tensor` parameter. Conceptually, inputs and final outputs of a computation are materialized, but that's an implementation detail. We implement just enough of `XLATensorImpl` to get the job done, there isn't a need for direct storage access to support PyTorch operations.

**Comment by kwgqjj** [comment]
ok, asuhan, i understand it, Thanks very much.

**Comment by chenweicdw** [comment]
For some reasons, is it possible to get the address of the real data when I forced it (for example, printing tmp), even I checked ComputationClient::ExecuteComputation, but I still can't get the real data, is there something I missed? Thanks very much.

**Comment by asuhan** [comment]
@chenweicdw Outputs from an XLA computation don't expose their underlying storage as pointers, so it's not possible to get the storage pointers. What are you trying to do? There should be ways to achieve it without having the storage pointers available.

**Comment by chenweicdw** [comment]
@asuhan 
Thanks very much for your answer. I want to get the storage pointers to construct the Memref Descriptor structure, then pass it as input to MLIR, the final goal is passing the real user input data to MLIR.
Is it possible to get the real data in XLATensorImpl? Thanks very much.

**Comment by asuhan** [comment]
@chenweicdw You can call `cpu()` on the XLA tensor from which you want the data, then use `storage()` to get a pointer to the storage you can then pass to MLIR. There's no "real" data in behind an XLA tensor until you actually force its evaluation, which `cpu()` does and it also transfers that data to host memory.

**Comment by chenweicdw** [comment]
@asuhan 
Thanks very much.

**Comment by chenweicdw** [comment]
@asuhan

**Comment by chenweicdw** [comment]
@asuhan 
Thanks very much. In python side, I can call XLATensor.cpu().storage() to get the real data, how about in C++ source code, I checked  the definition of XLATensor in tensor.h (~/pytorch/xla/torch_xla/csrc/tensor.h), it seems there is no cpu() method, it seems I should use GetTensors() method in C++, right? 
Thanks a lot.

**Comment by asuhan** [comment]
@chenweicdw `XLATensor::GetTensors()` would work, yes.

**Comment by chenweicdw** [comment]
@asuhan

**Comment by chenweicdw** [comment]
@asuhan 
Thanks a lot. 
I set a break point in the XLATensor::GetTensors() method, and when I force printing the result, the process will come to the break point, and then I tried to get the real data and address in gdb, it works.
But before I force printing the result, is it possible to get the input real data and address?
I tried an "add" op, and tried to call XLATensor::GetTensors() in ~/pytorch/xla/torch_xla/csrc/tensor_methods.cpp
XLATensor XLATensor::add(const XLATensor& input, const XLATensor& other, const at::Scalar& alpha, c10::optional<at::ScalarType> logical_element_type)
But when I tried to get the real data and address, the address is wired, I can't access that address.

(gdb) p input_data._M_impl._M_start.impl_.target_
$18 = (c10::TensorImpl *) 0x7fe9ec002810
(gdb) p input_data._M_impl._M_start.impl_.target_.storage_.data()
$19 = (void *) 0x3040200050403
(gdb) x/12u 0x3040200050403
0x3040200050403:	Cannot access memory at address 0x3040200050403

If I tried same way for output, I can access corresponding memory and get the real data.
Is there something I misunderstand? Thanks very much.

**Comment by asuhan** [comment]
@chenweicdw What's the address space of the `0x3040200050403` pointer, are you running on CPU? Because it doesn't look like CPU address space to me and of course you wouldn't be able to print its contents on host then, if it's GPU or TPU.

Also, did you call `XLATensor::GetTensors()` on the inputs or the output? Because if you call it on output, not sure what would you expect to happens for the inputs. You'd have to call it on each of the inputs if you want to look at their contents.

**Comment by chenweicdw** [comment]
@asuhan 
I call it on input, and I run on CPU in fact.
For example, I execute the following code in python:

import os
import torch
import torch_xla
import torch_xla.utils.utils as xu
import torch_xla.core.xla_model as xm
os.environ['XRT_DEVICE_MAP'] = 'CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0'
os.environ['XRT_WORKERS'] = 'localservice:0;grpc://localhost:40934'
device = xm.xla_device(devkind='CPU')

a_cpu = torch.tensor([[11, 12, 13],[21, 22, 23]])
a_xla = a_cpu.to(device)
b_cpu = torch.tensor([[31, 32, 33],[41, 42, 43]])
b_xla = b_cpu.to(device)
c_usingxla = torch.add(a_xla, b_xla)
print(c_usingxla)

And in ~/pytorch/xla/torch_xla/csrc/tensor_methods.cpp, I called GetTensors() method as follows. because the input data is passed here when I execute c_usingxla = torch.add(a_xla, b_xla).
Note: for convenience, I just removed the const determiner and simply construct std::vector<XLATensor>.

XLATensor XLATensor::add(/*modified: #const*/ XLATensor& input, const XLATensor& other,
                         const at::Scalar& alpha,
                         c10::optional<at::ScalarType> logical_element_type) {
  //added
  std::vector<XLATensor> input_vector;
  input_vector.push_back(input);
  auto input_data = XLATensor::GetTensors(&input_vector);
  //added

Then I tried to get the input_data real value and address, I got the above wired result.
