### ISSUE TITLE
python on XLA for CPU/GPU?

### ISSUE THREAD

**Issue by wangtz** [pytorch/xla#1448]
IIUC, with the same HLO, XLA is able to run on GPU and TPU. 

I wonder if this project allows running PyTorch on top of XLA for CPU/GPU and future AI chips (as soon as they support XLA)?

Thanks,
Tiezhen

**Comment by jysohn23** [comment]
Yes PyTorch models should be able to run with PT/XLA on GPUs as discussed in this thread: https://github.com/pytorch/xla/issues/694 although that isn't the focus for this project. 

Even for XLA_GPU there will be caveats such as XLA CRS not working for GPUs: https://github.com/pytorch/xla/issues/694#issuecomment-542683953.

That is my understanding too but @dlibenzi, the XLA expert, should know best 😄.

**Comment by dlibenzi** [comment]
XLA CPU is what we use 80% of the time during development on our workstation.
We run regressions internally, and the PyTorch CircleCI runs our (and their) tests on XLA CPU as well.
XLA GPU should work, but currently we would have to fix the XLA AllReduce() op on GPU.
XLA GPU only got very minor testing.
XLA TPU of course, is tested, and the main reason of this project.

But yes, since we lower to XLA, and chip supported by it, will be automatically usable.

**Comment by dlibenzi** [comment]
I have written a very (very) rough document of the steps I remember to have gone through to make putorch/xla GPU working.
[PyTorch_XLA_GPU.pdf](https://github.com/pytorch/xla/files/3989070/PyTorch_XLA_GPU.pdf)
