### ISSUE TITLE
automatic bfloat16 conversion

### ISSUE THREAD

**Issue by bkkaggle** [pytorch/xla#1489]
## ❓ Questions and Help

Hi, I have a question about bfloat16:

It says in [this](https://cloud.google.com/blog/products/ai-machine-learning/bfloat16-the-secret-to-high-performance-on-cloud-tpus) article that 

> When programming Cloud TPUs, the TPU software stack provides automatic format conversion: values are seamlessly converted between FP32 and bfloat16 by the XLA compiler which is capable of optimizing model performance by automatically expanding the use of bfloat16 as far as possible without materially changing the math in the model

Does the pytorch xla automatically chose what layers to keep in float32 and what layers to keep in bfloat16 when using `export XLA_USE_BF16=1`, or does it cast everything to bf16?

**Comment by dlibenzi** [comment]
There are 3 kinds of BF16 use in pytorch/xla.
The one that you cite above, is default in XLA.
Then there is the `export XLA_USE_BF16=1` setting, which transparently converts every `float32` to XLA BF16, **on device**.
The PyTorch user still sees `float32` as data type.
Then there is the new one, in which we map pytorch `bfloat16` data type, to XLA BF16.
The latter has not been tested much. Should work fine as long as all the ops are lowered by pytorch/xla, and no "come back to CPU" happen (since pytorch support for `bfloat16` on CPU is pretty slim to none).

**Comment by bkkaggle** [comment]
Thanks for the response, does this mean that by default, pytorch/xla is like apex's 02 mode?

**Comment by dlibenzi** [comment]
> Thanks for the response, does this mean that by default, pytorch/xla is like apex's 02 mode?

APEX O2 reasons more in terms of NN layers, as it hooks into the `forward()`.
That XLA Mode reasons in term of low level operations (matmul, conv, ...).

**Comment by dlibenzi** [comment]
You can use the following to always use higher precision in XLA:
```Python
torch_xla._XLAC._xla_set_use_full_mat_mul_precision(True)
```
