### ISSUE TITLE
Need `all_reduce` to collect validation results from different devices.

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#1555]
## 🚀 Feature
Doesn't exist in torch-xla-0.5 but apparently does in current master, so should exist in torch-xla-nightly right? Should I use the nightly version? (when's the next release btw?)

**Comment by zcain117** [comment]
In general, we do recommend using `nightly`. We are working on making that more explicit in our documentation since 0.5 is getting pretty old at this point.

Our nightly docker image (`gcr.io/tpu-pytorch/xla:nightly`) should be up to date with master.

Our pytorch-nightly VM image on Google Cloud is a few days behind  but it should include commits up to Jan 10 and it should be fully up to date within a day or two - we're fixing the job that publishes that image right now.

**Comment by dlibenzi** [comment]
The issue is that there is a coupling from the TF client version we link as submodule, and the TPU service we run in the TPU VM.
So one cannot use two that are not coupled.
Explicit stable releases are coupled (ie, 0.5 client with 0.5 TPU VM version), and nightly are.
Cannot match client nightly with TPU VM 0.5.

**Comment by harpone** [comment]
OK thanks! Is it safe to use the git master with the TPU nightly?
