### ISSUE TITLE
Training on TPU Pod on Single VM

### ISSUE THREAD

**Issue by NaxAlpha** [pytorch/xla#1858]
## ❓ Questions and Help

I want to train my model on TPU pod but is it possible to use do distributed training on single VM rather than using a cluster/instance group?

Thanks

**Comment by dlibenzi** [comment]
Even though the current 1:1 mapping between user and TPU VMs could be loosened (but we currently do not support it), there is no way one could drive a POD from a single user VM.

**Comment by shawwn** [comment]
Why not?

Tensorflow uses an `n1-standard-2` instance. 2vCPU + 8GB RAM. Drives pods all day. I trained a resnet classifier using a TPUv3-1024 in less than 3 minutes using it.

**Comment by dlibenzi** [comment]
Because you did it with TF.
TF has a dedicated TF server running on the TPU VM (a part of it is what we also use), so the TF running on a user VM is just a shim that does nothing.
So in TF you shoot the graph on the TPU VMs side, and all the input pipelines run on the TPU VMs resources (which are pretty rich in terms on CPU and RAM).
In PyTorch the input pipelines run on the user VMs, and there is no dedicated PyTorch server on the TPU VM side.
And also the PyTorch pipelines semantics are different from the PyTorch ones as they born from Day 0 to be graph-building interfaces, as opposed to local-processing ones.

**Comment by shawwn** [comment]
Yes, but that approach has several important limitations.

- The TPU's CPU is right next to the TPU cores. Presumably each TPU CPU has a high-speed link to all 8 cores. In my experiments, a single VM in GCE is only able to get 1Gbit/s. The TPUv3-1024 resnet benchmark gets 600,000 examples/sec. A TPUv3-1024 has 128 CPUs, so that's 4,687 images per second per CPU. Imagenet's total size is 163GB, so 163GB / 1.2M = ~140KB per image. So with this design, you'd have to push 140KB * 4,687 examples/sec = 656MB, aka 5 gigabits per second, every second, from 128 different VMs in GCE, on average, just to barely match their training speed.

- The datasets have to be transferred to all VMs. If your dataset is 160GB, that means you have to distribute 160GB to 128 different VMs to drive a 1,024-core TPU pod.

- Each TPU CPU can allocate up to 300GB without running out of memory. (Yes, 300GB -- not a typo.) Although normally you don't *need* to allocate 300GB per VM, you still can. Previous discussion, where I take advantage of this technique to train GPT-2 1.5B with a batch size of 4 using Adam, which is normally impossible: https://github.com/google/jax/issues/2108#issuecomment-581539812

So, given that this approach doesn't scale, what would it take to implement support for the TPU's CPU into pytorch XLA (or Jax, for that matter)? Can we help somehow?

The overall goal is to match Tensorflow's TPU training speed, isn't it? https://twitter.com/theshawwn/status/1234654848114520065 Otherwise, why use TPUs at all? A GPU farm will give you just as much advantage, and it's probably cheaper.

**Comment by dlibenzi** [comment]
Any effort in that space will be wasted, as we are migrating the Cloud TPU infrastructure to not use two separate VMs anymore.
TF will be in the same ballpark of PyTorch, with a single VM, and same resources (of the TPU VM side).

**Comment by shawwn** [comment]
Excellent. So, if I understand you correctly, in the future, a single VM will be sufficient to drive a TPU pod using pytorch XLA. In that case, could we loosen the current 1:1 mapping between user and TPU VMs so that we can test that our code works on TPU pods? Is this something we could do ourselves?

If the mapping is defined somewhere in the pytorch/xla codebase, can we (in principle) fork the codebase, override the mapping, and then use that fork in our experiments? If so, could you point us towards which section of the code handles that?

**Comment by dlibenzi** [comment]
No.
In the future it will be the same exact current architecture for PyTorch.
But there won't be, given a POD having N TPU VMs, anymore N TPU VMs plus N user VMs, but just N TPU VMs where the PyTorch client mesh will run.
So the input pipelines will run with higher resource limits, and w/out any code changes on our side (besides the core ones in the computation client and some minor ones in xla_dist.py).

You cannot run any experiments as there is no support from both Cloud TPU and the new libraries we will have to use in the new world to implement the computations client.

**Comment by shawwn** [comment]
Will this new input pipeline support reading tfrecords directly from google cloud buckets? The dataset won't pass through the user VM, right?

Right now we have several terabytes of data in our buckets, and we frequently kick off training runs in various dataset configurations. Any system where we have to download the data to a VM would make this impossible.

**Comment by dlibenzi** [comment]
Yes, data will be read directly from GCS buckets into the VM where both PyTorch and the TPU HW resides.
No more bouncing from the user VM to the TPU VM.
We provide support for both TF record decoding and GCS file access:

https://github.com/pytorch/xla/blob/master/torch_xla/utils/tf_record_reader.py
https://github.com/pytorch/xla/blob/master/torch_xla/utils/gcsfs.py

We have not built yet PyTorch input pipelines able to take advantage of the above components.

**Comment by shawwn** [comment]
Excellent. I am extremely happy and relieved to hear that. We knew you had some sort of plan, but I was getting slightly nervous that whatever you came up with was going to have serious limitations. But based on this conversation, it sounds like the current limitations are temporary.

Two questions:

1. We noticed the tf_record_reader op a few days ago. Is there any code, anywhere (even a short snippet, or *anything*) showing how to use it in a real, working program? We'll take any scrap of information we can get.

2. Everyone's favorite question: Any idea when the new changes will be live? Is there any possible way we could get early access? We have several interesting codebases to port: GPT-2, StyleGAN2, etc. Obviously, we'd provide lots of bug reports and API feedback, if it helps.

**Comment by dlibenzi** [comment]
This is an old snippet I had (the example decodes the imagenet format we have):

https://gist.github.com/dlibenzi/25a7e7a78df718684b9af3468b59b1d7

Keep in mind that a TfRecord is just a bunch of fields, and each dataset will have its own format.

I am not able to provide timelines at this time, sorry.

**Comment by shawwn** [comment]
Hmm, interesting. It looks like the path is `/tmp/tf_images`. Do you think this would work for tfrecords stored in a cloud bucket? If not, is it possible (in principle) to use the functionality from gcsfs.py to somehow pass the data to tf_record_reader op without the data being downloaded to the user's VM?

**Comment by shawwn** [comment]
(Or more generally, "Do you think it's possible for me to use this op on a TPU today?" -- I was planning on trying to copy your code into a pytorch TPU notebook and point it at a gs:// path.)

**Comment by shawwn** [comment]
Oh! I'm sorry, `/tmp/tf_images` is the path that it writes to. I see that the path that it reads from gets read from stdin.

I'll try this using a `gs://` path right now. Thanks again!

**Comment by dlibenzi** [comment]
That's just dummy code 😄 
The path passed to the TF record reader should accept `gs://` paths.

**Comment by shawwn** [comment]
It worked!

![image](https://user-images.githubusercontent.com/59632/78161649-a24a0680-73fa-11ea-9f9c-565916b1f660.png)

Incredible. How do I verify this is really running on a TPU? i.e. no data is transferred to the colab notebook.

I'm not sure how to tell the internal operations to "use a specific TPU core." E.g. `second_dev = xm.xla_device(n=2, devkind='TPU')` -- where should I pass `second_dev` to? `tf_record_reader` doesn't seem to take a `device` argument.

Should I put a `.to(second_dev)` somewhere in the `decode` function?

This is really neat! Thank you.

**Comment by NaxAlpha** [comment]
Just to add here, my use-case does not require data I/O from the bucket and so far i have been using xla for single TPU which works by forking multiple processes for each TPU core. 

So theoretically it should be possible to just fork as many processes for every TPU core in a TPU pod and assign TPU Node as well as core of that node to that process. i.e. for TPU Pod v3-32, one may use 32 processes within a single VM instead of spawning 4 VMs and each VM with 8 processes etc. So what are the challenges in this approach?

**Comment by dlibenzi** [comment]
> It worked!
> 
> ![image](https://user-images.githubusercontent.com/59632/78161649-a24a0680-73fa-11ea-9f9c-565916b1f660.png)
> 
> Incredible. How do I verify this is really running on a TPU? i.e. no data is transferred to the colab notebook.
> 
> I'm not sure how to tell the internal operations to "use a specific TPU core." E.g. `second_dev = xm.xla_device(n=2, devkind='TPU')` -- where should I pass `second_dev` to? `tf_record_reader` doesn't seem to take a `device` argument.
> 
> Should I put a `.to(second_dev)` somewhere in the `decode` function?
> 
> This is really neat! Thank you.

I would start by reading our documentation and looking at the examples.

**Comment by dlibenzi** [comment]
> Just to add here, my use-case does not require data I/O from the bucket and so far i have been using xla for single TPU which works by forking multiple processes for each TPU core.
> 
> So theoretically it should be possible to just fork as many processes for every TPU core in a TPU pod and assign TPU Node as well as core of that node to that process. i.e. for TPU Pod v3-32, one may use 32 processes within a single VM instead of spawning 4 VMs and each VM with 8 processes etc. So what are the challenges in this approach?

Doesn't your model take any input?
Does not matter whether bucket or not.
Inputs will have to be processed (CPU+RAM on the user VM), and sent to the TPU VMs (network bandwidth) ... multiplied by 32.

**Comment by NaxAlpha** [comment]
It takes input but since i am training language model single batch is 4096 integers but yes processing happens (just padding with zeros) but that is very small compared to if i were training imagenet which would have required a lot of client side processing.

**Comment by dlibenzi** [comment]
We will look into enabling that.
Granted, 32 processes, each creating many threads, ... you need to have a pretty beefy user VM to do that.

**Comment by tyoc213** [comment]
> In the future it will be the same exact current architecture for PyTorch.
> But there won't be, given a POD having N TPU VMs, anymore N TPU VMs plus N user VMs, but just N TPU VMs where the PyTorch client mesh will run.

Is There an ETA for this?

**Comment by jysohn23** [comment]
That feature should be coming in the next couple months.

cc: @JackCaoG

**Comment by JackCaoG** [comment]
@tyoc213 My best guess is sometime in the early 2021. We will give you better updates when the date become closer.

**Comment by turian** [comment]
@JackCaoG Any update? Why is this issue closed?
