### ISSUE TITLE
low memory causes rendezvous error

### ISSUE THREAD

**Issue by btomtom5** [pytorch/xla#2190]
## To Reproduce

https://colab.research.google.com/drive/1yv3uawP0ZHRfc0wNW4Ag771Icn7CCXJS?usp=sharing

## Expected behavior

I expect the code to run without errors, but it instead causes a rendezvous failed to meet error. I've found that the error will go away when it is run on a High-ram TPU instance but will appear again in a regular TPU instance.

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:
 - Any other relevant information. In case of issues related to slow executions, re-compilations, etc.., it is useful to have the `tar.gz` report from https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information

**Comment by dlibenzi** [comment]
We know about this, and this only happens if after the rendezvous the processes exit.
We need to find a solution that does not sucks as adding this after the last rendezvous:
```Python
  if index == 0:
    time.sleep(2)
```
The error is due to the mesh master exiting before they mesh clients gets the final responses.
IMO is a GRPC issue, because it seems the socket close event gets delivered even though the clients after getting the response are going to exit.

**Comment by dlibenzi** [comment]
Oh, and memory does not really matter. Might change the timing and hence make things work.

**Comment by dlibenzi** [comment]
Refer to https://github.com/pytorch/xla/issues/2246
