### ISSUE TITLE
can pytorch/xla support  `tf.xla.experimental.jit_scope():` at GPU devices

### ISSUE THREAD

**Issue by qianzhang613** [pytorch/xla#2305]
## 🚀 Feature

is there has any plan to support with tf.xla.experimental.jit_scope() or how to implement this feature?

## Motivation

we want use xla just as same as  tensorflow  to accelerate pytroch training at GPU deivces.  unlike tpu, it is did not necessary to transfer every ops to xla backend,  As some ops pytorch aten works well,  is there a way to mix pytorch gpu backend and xla GPU backend?

## Pitch

may be just like  `tf.xla.experimental.jit_scope()` , which only compile the code in the scope?

**Comment by qianzhang613** [comment]
@ailzhang @JackCaoG  could someone give some instructions?
thanks very much~

**Comment by dlibenzi** [comment]
It is not supported and likely never will.
In pytorch you can just move data onto pytorch CUDA devices and do ops there.
You will need to have some major time savings to make up the time spent moving back and forth data in/out devices though.

**Comment by qianzhang613** [comment]
> It is not supported and likely never will.
> In pytorch you can just move data onto pytorch CUDA devices and do ops there.
> You will need to have some major time savings to make up the time spent moving back and forth data in/out devices though.

in my opinion, XLA  did some compute graph optimize and compute ops fused  that can be to   accelerate train speed fast than  pytroch CUDA ops ?

**Comment by ailzhang** [comment]
Currently if you want to mix pytorch gpu backend and xla gpu backend computation, you'll have to do something like 
```
input = input.cuda()
result = torch.blah(input) # use pytorch GPU backend to do computations
xla_input = result.cpu().to('xla') # setup and use pytorch/xla GPU backend
# the computation on xla backend will be lazily accumulated in graph and optimized
xla_result = torch.blah(xla_input, xla_input)
```
But this is not a common use case so whether you'll get perf boost depends on how you partition your computation between pytorch GPU and pytorch/xla GPU backend and whether XLA has an optimization for it. 
It's possible that we make this user experience easier if it shows real perf gains, but this is an enhancement instead of top priority on our list for now.

**Comment by qianzhang613** [comment]
i got it, thanks @ailzhang
