### ISSUE TITLE
support for pytorch geometric  and Deep graph library

### ISSUE THREAD

**Issue by trinayan** [pytorch/xla#2473]
Hi,

I am trying to run a graph neural network developed on the pytorch geometric package on a TPU using Pytorch XLA. Are all frameworks based on pytorch  such as pytorch geometric and Deep Graph Library supported using this Pytorch XLA?. I tried a few models and it ran into a bunch of errors. I believe the reason is that these frameworks use their own custom kernels and functions that are not part of the official pytorch package. So I am wondering what is the level of effort that would be required to enable pytorch xla to work with such frameworks?. Some high level information would be really useful. Thanks.

Best,
Trinayan

**Comment by jysohn23** [comment]
Our https://github.com/pytorch/xla/blob/master/API_GUIDE.md would be a good place to start on learning about how and which APIs need to be changed to use XLA devices. We haven't tried GNNs with PT/XLA ourselves. As long as it has custom kernels/ops outside of the main model and instead in places like the input preprocessing it should be fine. However, if it has custom ops in the model training graph, then that'd be a problem since for those we don't have corresponding lowering so there'd be high cost associated with fetching TPU device data back to CPU, running the custom op, and placing it back on TPU device.
