### ISSUE TITLE
Use torch_xla Together with TF

### ISSUE THREAD

**Issue by yaochengji** [pytorch/xla#2524]
## 🐛 Bug

The following two python lines could reproduce.

`
F tensorflow/core/framework/variant_op_registry.cc:46] Check failed: existing == nullptr (0x3dd5328 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::data::WrappedDatasetVariant already registered
Aborted (core dumped)
`

## To Reproduce

import tensorflow as tf
import torch_xla

**Comment by jysohn23** [comment]
Hi @yaochengji this is  a known issue on our side as we build and carry TF as a dependency in `torch_xla`. What's the use case that you need to use both tensorflow and torch_xla together?

**Comment by yaochengji** [comment]
Thanks @jysohn23. I use TF to process TFRecord data.

**Comment by jysohn23** [comment]
We do have a record reader in `torch_xla` for this reason here:

https://github.com/pytorch/xla/blob/master/torch_xla/utils/tf_record_reader.py#L7

Does this work for you?

**Comment by yaochengji** [comment]
Thanks. Let me have a try.

**Comment by rwightman** [comment]
@jysohn23 I've got a use case where I'd prefer to use a wrapper I've written around TFDS instead of using tf_record_reader ... reason, I want to use some out-of-the box TFDS datasets for transfer learning experiments and use consistent splits, etc.

Are there any workarounds possible?

**Comment by rwightman** [comment]
For reference, this is the TFDS wrapper I've written. Still not perfect in some split/sharding situations, but I've used it for Imagenet-1k, birds, and pets quite a bit already 
https://github.com/rwightman/pytorch-image-models/blob/master/timm/data/parsers/parser_tfds.py

**Comment by jysohn23** [comment]
Thanks Ross. I haven't had the time to look today, but I'll take a look next week.

**Comment by rwightman** [comment]
@jysohn23 no rush, it is working for some reason on the tpuvm default python3 env, including the latest version with 1.8.1. 

I just had to update tensorflow since the default TF installed in tpuvm is missing GS bucket reading support. But installing tensorflow-datasets  on the PyTorch XLA CUDA docker nightly leads to the VariantDecodeFn error that started this issue when running with XLA GPU. I need to look a bit closer and see if I can spot differences in the the envs, or maybe different bits of tensorflow get imported if a GPU is present?
