### ISSUE TITLE
fairseq doesn't work on v32 but works on v8

### ISSUE THREAD

**Issue by xwuShirley** [pytorch/xla#2569]
## 🐛 Bug
Hi there,

We have a problem using distributed training with v2-32. The same code and data work very well on v3-8 TPU (log is here)
https://drive.google.com/file/d/1fbBpZ-0pmNPH-Ec2xDcysD7LRXCg5jG2/view?usp=sharing 

However, while using v2-32, it failed log is here
https://drive.google.com/file/d/1ZoUNa60hFhdkjeZpLjVtt-sY3xMigP1l/view?usp=sharing (this file is 140MB)

It seems that the code is able to do the forward pass but fail on the backpropagation. 
We don't know what the error means when reading the v2-32 log.  We would really appreciate if you could give some hint! 

Thanks! 

 with @kkissmart

**Comment by zcain117** [comment]
Sorry those logs are pretty miserable to read since they dump out the entire XLA graph.

In there I see this:
`2020-10-22 02:48:58 10.128.0.33 [3]   (1) Resource exhausted: Attempting to allocate 180.59M. That was not possible. There are 142.58M free.; (0x3x0_HBM1)`

Often we fix this by using smaller batch size. Btw, a v3-x would have more HBM memory. How does your v2-8 batch size compare to your v2-32 batch size?

**Comment by xwuShirley** [comment]
Great! thank you so much! We halved the batch-size and the code successfully worked.
