### ISSUE TITLE
things being slow inside docker file

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2611]
Hi
I am docker file to run a code (huggingface t5 model) with pytorch xla, here is the command

docker run -it --shm-size 100G    -e XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"   --volume /home/rabeeh/seq2seq/:/home/rabeeh

the first time I enter the container, things run, then it becomes incredibly slow like really slow the second time, if the program crash in between thanks

**Comment by zcain117** [comment]
So this problem only happens if you run once, then the program crashes, then you try running again?
If so, you could try resetting the TPU between runs by stopping and starting the TPU in the Google Compute Engine's TPU page

I was also wondering if you are seeing the same issue when running the model using our conda env: https://github.com/pytorch/xla#-consume-prebuilt-compute-vm-images
