### ISSUE TITLE
xm.save on gs bucket 

### ISSUE THREAD

**Issue by cameronalonso2** [pytorch/xla#2648]
Hi
I need to save the model directly on my bucket on cloud, could you tell me how I can change xm.save to save the modle in bucket. thanks

**Comment by zcain117** [comment]
We have a GCS util here: https://pytorch.org/xla/release/1.7/index.html#torch_xla.utils.gcsfs.open

Some examples of using it: https://github.com/pytorch/xla/blob/master/test/gcsfs_test.py

You can see `xm.save` code here: https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L787

You could make a similar helper method to `xm.save` that uses GCSFS instead of `torch.save`
