### ISSUE TITLE
MpDeviceLoader seems 15x slower than DataLoader

### ISSUE THREAD

**Issue by foobar8675** [pytorch/xla#2699]
Using the flowers dataset, I have 2 simplfied colab notebooks, where using `MpDeviceLoader` loading a batch is about 5 seconds and `DataLoader` is about .3 seconds. Am I doing something wrong?

tpu version
https://colab.research.google.com/drive/1jPf_bHgNXafWQ4X_jCPTtBjMBhoFKNKL?usp=sharing

gpu version
https://colab.research.google.com/drive/1d9oyn9lYGeZl3JeBUgzn-I9KdhjQpx2L?usp=sharing

**Comment by zcain117** [comment]
Could you also compare `DataLoader` to `MpDeviceLoader` on TPU?

I predict GPU vs TPU is making a bigger difference than `DataLoader` vs `MpDeviceLoader` but would like to see your results.

Data transfer is more expensive with TPU because the TPU lives on a separate machine where GPUs are on the host VM, among other reasons. On TPU it's important to minimize data transfer as much as possible (use large batch size, avoid `.item()` calls, etc). On the models we officially support, the TPU speed is so high that it makes up for the the slower data transfer and the overall train time is faster on TPUs

Another thing that helps TPU speed when doing real training is that we are able to pipeline the work a bit such that the dataloader can be loading data while the TPU is processing a batch.

**Comment by foobar8675** [comment]
hi @zcain117 ,  `DataLoader` on tpu runs at about .6 seconds per batch.

https://colab.research.google.com/drive/1qKCV0GMpwSOAeZtn83fQlZ2kO5JjYAEC?usp=sharing

**Comment by zcain117** [comment]
Thanks for checking that. We do use `enumerate` in all our example colab notebooks and example tests like [here](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L203)

**Comment by foobar8675** [comment]
Ah, ic. got it, thanks. Just curious, do you know why `enumerate` is so much faster?

**Comment by zcain117** [comment]
One thing I notice is that in your `next` loops, you are creating a new iterator on every pass of the loop since you are calling `iter()` on every pass. Not sure if that was intended for the speed test

Example:

```
>>> a = ['a', 'b', 'c', 'd', 'e']
>>> b = iter(a)
>>> for i in range(3):
...   print(next(b))   # This is what's happening in the enumerate case
... 
a
b
c
>>> for i in range(3):
...   print(next(iter(a)))   # This is what's happening in your other case
... 
a
a
a
>>> 
```

**Comment by zcain117** [comment]
Adding on to my previous comment, in your `enumerate` case, you can see the first pass of the loop is slower and subsequent passes are fast:

```
enumerate MpDeviceLoader (superfast)
[ ]
t = time.time()
for n_batch, (real_batch) in enumerate(loader):
    print(f"duration {time.time()-t} {real_batch.shape}")
    t = time.time()
    if n_batch > 10:
        break

duration 2.541928768157959 torch.Size([32, 3, 256, 256])
duration 0.00015854835510253906 torch.Size([32, 3, 256, 256])
duration 5.2928924560546875e-05 torch.Size([32, 3, 256, 256])
duration 4.458427429199219e-05 torch.Size([32, 3, 256, 256])
duration 1.5831737518310547 torch.Size([32, 3, 256, 256])
duration 0.0005791187286376953 torch.Size([32, 3, 256, 256])
duration 7.462501525878906e-05 torch.Size([32, 3, 256, 256])
duration 5.7697296142578125e-05 torch.Size([32, 3, 256, 256])
duration 1.6219482421875 torch.Size([32, 3, 256, 256])
duration 0.0001575946807861328 torch.Size([32, 3, 256, 256])
duration 4.8160552978515625e-05 torch.Size([32, 3, 256, 256])
duration 4.124641418457031e-05 torch.Size([32, 3, 256, 256])
```

In the `next(iter())` case, every pass is slow:
```
duration 2.591979503631592
duration 3.3128280639648438
duration 4.578497648239136
duration 4.622112989425659
duration 4.524408578872681
duration 5.133802652359009
duration 4.9301512241363525
duration 4.921796560287476
duration 5.040240526199341
duration 5.075345277786255
```
The first pass of each version is the same duration

So my guess is that the first call is slower since that's where the iterator is being setup and maybe there is more setup required in the [MpDeviceLoader class](https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L178) which calls into `ParallelLoader` which has [non-trivial init](https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L69)

**Comment by foobar8675** [comment]
I think that's a great guess. Thanks for explaining @zcain117
