### ISSUE TITLE
get_xla_supported_devices always returning `xla:0`

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#2728]
## 🐛 Bug

The function should return `xla:{n}` for device n but doesn't. I'm training with Pytorch Lightning on GCP VMs with torch-xla version 1.7.

## To Reproduce

Code from [here](https://github.com/pytorch/xla/blob/a2c0db47356a532d64b4445d9372b1291dfbbc9e/torch_xla/core/xla_model.py#L124):
```
def get_xla_supported_devices(devkind=None, max_devices=None):
  """Returns a list of supported devices of a given kind.

  Args:
    devkind (string..., optional): If specified, one of `TPU`, `GPU` or `CPU`
      (the 'GPU' XLA device is currently not implemented).
    max_devices (int, optional): The maximum number of devices to be returned of
      that kind.

  Returns:
    The list of device strings.
  """
  xla_devices = _DEVICES.value
  devkind = [devkind] if devkind else ['TPU', 'GPU', 'CPU']
  for kind in devkind:
    kind_devices = []
    for i, device in enumerate(xla_devices):
      if re.match(kind + r':\d+$', device):
        kind_devices.append('xla:{}'.format(i))
    if kind_devices:
      return kind_devices[:max_devices] if max_devices else kind_devices
```

1. Training job is launched with 'fork' method with PTL (should this be 'spawn' when using a cloud VM?). Then `get_xla_supported_devices` is called on each forked process. `xla_devices = _DEVICES.value` gives `['TPU:n']` for n in 1...8 as expected. Note that the list has only the single TPU core, not all cores. In this case, since the list length is 1, the function will actually *always* return 'xla:0' instead of 'xla:n'.

This results in `xm.xla_device()` always returning `xla:0` (except actually returns `xla:1` for the main process).

Possible solutions:
1. Modify `get_xla_supported_devices` to catch the correct TPU core index when `_DEVICES.value` contains only one core
2. If this is expected behavior, change PTL to explicitly define the correct TPU by `tpu_device = xm.xla_device(trainer.tpu_id)` (for some reason this doesn't happen now... will investigate).

## Environment

 - Reproducible on XLA backend: TPU
 - torch_xla version: 1.7
 - GCP VM with debian-9-torch-xla-v20201214 image

## Additional context
- I'll see if I can make PTL assign the correct TPU id
- I'll try out the torch-xla nightly version

**Comment by harpone** [comment]
`tpu_device = xm.xla_device(trainer.tpu_id)` does not work apparently because the forked process sees only one TPU core... 

so I think `_DEVICES.value` should always display all the TPU cores, not just the core corresponding to the current process? Things should probably work then...

**Comment by jysohn23** [comment]
@zcain117 for PTL

There's ordering in the device `xla:0` when launched in a multiprocessing context. Instead if you want the device ordinal you should instead use `xm.get_ordinal` https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L161.

`_DEVICES.value` returns the devices that are local to the current process, so under a multiprocessing context (fork/spawn) that'd be the single device that the process is handling https://github.com/pytorch/xla/blob/3eaee46ef679cc6a0f1f694bd0a007dbfd09c51b/third_party/xla_client/xrt_computation_client.h#L129-L132

However, in a multithreading context (which is discouraged from being used as you're quickly bottlenecked by the python GIL), you'd see multiple devices since one process is driving multiple devices.

**Comment by harpone** [comment]
Ah OK thanks for the info! So I guess it's PTL doing something funny with the TPU core assignment... I'll post an issue there (but keeping this open for a while if OK).

**Comment by harpone** [comment]
hmm I guess something changed in the nightly version, since that's working now! Don't know what it was but I'm closing.
