### ISSUE TITLE
Using xmp.spawn, state_dict gets locked and the model can't be saved.

### ISSUE THREAD

**Issue by tchaton** [pytorch/xla#2772]
## To Reproduce

Here is the current PR I am working on: https://github.com/PyTorchLightning/pytorch-lightning/pull/5878/files
It seems I can't save the model as it gets locked.
Any idea ?

1.
2.
3.

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:

**Comment by taylanbil** [comment]
That's a big pr, haven't been able to look at all of it, but usually the hang during `xm.save` is due to the [rendezvous](https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L819) at the end. If for some reason, each and every core doesn't arrive at the rendezvous, process will hang.

This happens, for example, when users have an if statement around `xm.save`, which for some cores become True and for others, False. If I recall correctly, PT lightning was interested in running a different workload in all cores, which would likely end up in this state. Is it certain that all cores arrive at this xm.save call simultaneously?

**Comment by zcain117** [comment]
Also curious: does this happen when you run `tpu_cores=1` or some other method of running on just 1 core?  If it doesn't happen there, that's more evidence of Taylan's theory of different cores not reaching the rendezvous.

If you're using 8 cores with the normal `xmp.spawn`, then you don't need any `if` statement since `xm.save` will already make sure that only the master core performs the write: https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L813

**Comment by Halmoni100** [comment]
I am having a similar issue where the code is hanging when trying to move a tensor from TPU in xmp.spawn to CPU with more than one process.  Seems to work fine with a single process.
