### ISSUE TITLE
randn causes recompile even data shapes are unchanged

### ISSUE THREAD

**Issue by mli** [pytorch/xla#2783]
I run the following code and expect it should be compiled once as data shapes are not changed.

```
dev = xm.xla_device()
for _ in range(10):
  n = 1024
  a = torch.randn(n, n, device=dev)
  b = torch.randn(n, n, device=dev)
  y = torch.matmul(a,b)
  _ = float(y.sum())
```

but according the metric, every execution caused a compilation, which causes a big performance issue. Is there any specialty in randn causes this behavior? 

```
etric: CompileTime
  TotalSamples: 66
  Accumulator: 21s763ms675.999us
  ValueRate: 446ms519.426us / second
  Rate: 1.41621 / second
  Percentiles: 1%=007ms617.270us; 5%=007ms859.908us; 10%=007ms975.321us; 20%=007ms130.260us; 50%=008ms685.125us; 80%=690ms589.001us; 90%=932ms976.553us; 95%=962ms659.163us; 99%=997ms323.988us
Metric: DeviceLockWait
  TotalSamples: 66
  Accumulator: 209.786us
  ValueRate: 004.531us / second
  Rate: 1.42563 / second
  Percentiles: 1%=001.313us; 5%=001.559us; 10%=001.606us; 20%=002.163us; 50%=003.126us; 80%=003.981us; 90%=004.180us; 95%=004.460us; 99%=009.836us
Metric: ExecuteTime
  TotalSamples: 66
  Accumulator: 365ms698.109us
  ValueRate: 008ms826.704us / second
  Rate: 1.41641 / second
  Percentiles: 1%=002ms223.452us; 5%=002ms439.730us; 10%=003ms515.012us; 20%=003ms632.620us; 50%=003ms153.556us; 80%=008ms318.961us; 90%=009ms390.687us; 95%=010ms832.600us; 99%=042ms689.780us
```

**Comment by taylanbil** [comment]
Could you remove the float() call, set `_ = y.sum()` and add a `xm.mark_step()` after that line?

```python
dev = xm.xla_device()
for _ in range(10):
  n = 1024
  a = torch.randn(n, n, device=dev)
  b = torch.randn(n, n, device=dev)
  y = torch.matmul(a,b)
  _ = y.sum()
  xm.mark_step()
```

**Comment by yzhliu** [comment]
@taylanbil that triggers only 1 compilation. any idea what causes the difference?

**Comment by taylanbil** [comment]
So what's happening underneath is roughly as follows:

- Python code such as `torch.matmul(a,b)` doesn't actually execute the matrix multiplication, but it appends this operation to the IR graph, which is to be executed later by the XLA device.
- Device executes (after it compiles if needed) when it sees `xm.mark_step()`. This function materializes all live tensors.
- so in a for loop w/o `xm.mark_step()`, the code from the first comment ends up constructing 1 large graph (containing 10 steps because of `range(10)`)
- That would still compile only once, but there's one more quirk:
- the line w/ `float(y.sum())` triggers an early compilation + execution + context switch from tpu to cpu.
- the nth time we see `float(y.sum())`, the active graph contains n-1 iterations of the loop, so it's unseen before => needs to compile.
- In fact, I'm not sure if a previously seen graph compiles or not if it's triggered via early execution. It probably compiles every time even if it's seen before, due to it being premature execution.

So w/ the changes I introduced;

- We mark step and materialize tensors, so there's 1 graph per loop iteration.
- there's no more `float(tensor)`, so no more early execution.
- 1 graph total => 1 compilation.

**Comment by taylanbil** [comment]
Since `torch.randn` works fine, I'm going to go ahead and close this. Please re-open if needed, and don't hesitate to follow-up w/ questions if there are any. Thanks.

**Comment by yzhliu** [comment]
@taylanbil I don't think it's due to early compilation `float(...)`, if we replace `torch.randn` with `np.random.randn` and `torch.from_numpy`, everything looks as expected,

```python
dev = xm.xla_device()
n = 8

def matmul():
  #a = torch.randn(n, n, device=dev)
  #b = torch.randn(n, n, device=dev)
  anp = np.random.randn(n, n)
  bnp = np.random.randn(n, n)
  a = torch.from_numpy(anp).to(device=dev)
  b = torch.from_numpy(bnp).to(device=dev)
  y = torch.matmul(a,b)
  return float(y.sum())

%timeit -n 10 matmul()
print(met.metrics_report())
```
compilation triggers only once,

```
10 loops, best of 3: 10.3 ms per loop
Metric: CompileTime
  TotalSamples: 1
  Accumulator: 103ms821.957us
  Percentiles: 1%=103ms821.957us; 5%=103ms821.957us; 10%=103ms821.957us; 20%=103ms821.957us; 50%=103ms821.957us; 80%=103ms821.957us; 90%=103ms821.957us; 95%=103ms821.957us; 99%=103ms821.957us
Metric: DeviceLockWait
  TotalSamples: 30
  Accumulator: 107.210us
  ValueRate: 183.339us / second
  Rate: 51.3027 / second
  Percentiles: 1%=002.777us; 5%=002.817us; 10%=002.848us; 20%=002.887us; 50%=003.235us; 80%=003.905us; 90%=004.963us; 95%=006.562us; 99%=008.504us
Metric: ExecuteTime
  TotalSamples: 30
  Accumulator: 269ms080.778us
  ValueRate: 568ms799.472us / second
  Rate: 63.3044 / second
  Percentiles: 1%=002ms329.057us; 5%=002ms369.673us; 10%=003ms634.795us; 20%=003ms862.643us; 50%=003ms054.407us; 80%=010ms561.820us; 90%=024ms822.109us; 95%=046ms059.500us; 99%=090ms616.018us
Metric: InboundData
```

**Comment by taylanbil** [comment]
In [previous comment](https://github.com/pytorch/xla/issues/2783#issuecomment-782215286) context has changed a little bit, let me explain;

- If you use `np.randn`, xla has no idea a random operation has taken place, so every graph that it sees is one single `matmul`.
- Therefore in that case there's only 1 compilation triggered by the `float` call, even though you're not marking step. (and that clarifies my confusion about caching compilations of premature executions)
- If you use `torch.randn`, the actual graph contains the splitting of the RNG seed at the XLA level. Since you're not marking step, and the executions are premature, triggered by `float`, the 2nd iteration's graph contains
  - pull graph1's RNG seed from device data
  - graph1's RNG seed moving forward to become graph2s RNG seed
  - generate randn tensor
  - matmul
- If you didn't have `float`, and marked step at the end of the `matmul` function, the graph of 2nd iteration would look like this:
  - pull graph2s RNG seed from device data, which is already materialized at this point, and XLA doesn't need to recompute it from graph1's seed.
  - generate randn tensor.
  - matmul
- In the former case, all the graphs differ, because Nth iteration moves graph1's seed forward N-1 times, causing N compilations.
- In the latter case, all graphs are the same ==> 1 compilation.

I don't know how interesting this specific example is, but I'd write this code snippet as follows for good performance:
```python
dev = xm.xla_device()
for _ in range(10):
  n = 1024
  a = torch.randn(n, n, device=dev)
  b = torch.randn(n, n, device=dev)
  y = torch.matmul(a,b)
  _ = y.sum()
  xm.mark_step()
  floatvalue = float(y)
```

Since y is materialized by the markstep call, calling float on it is cheap, meaning there's no compilation/early execution and it's a single transfer from device to CPU.

**Comment by mli** [comment]
Thanks for your very detailed explanation, @taylanbil 

An additional question about the cost when `mark_step` is not used,  I'm not sure which one of the following is correct:

1. since the operator shape doesn't change, so there is no cost to re-compile `matmul` and `sum`. compile the graph means chains the cached operators's IR (very fast), but need some additional XLA pass (the main bottleneck)
2. no operator cache is used, so recompile the graph to IR directly anyway

**Comment by taylanbil** [comment]
I'd like to also point out that in real applications, we recommend using our wrapper loader as in [this example](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L232) which marks the step every time it yields the next batch, so user doesn't have to worry about marking step in code.

**Comment by taylanbil** [comment]
@mli I think the fact that the code w/ numpy from https://github.com/pytorch/xla/issues/2783#issuecomment-782215286 compiles only once shows that in the event that no mark_step is called and everything is triggered by early execution, there's no cost to re-compile matmul and sum (and other ops that doesn't create a different graph every time they are called. It's just that randn involves the moving of RNG seed forward, which changes the graph.). I would heavily recommend not relying on early executions though, if you wanted to run a real workload. There's no huge cost to marking step, and things flow much better if steps are marked. Not to mention if the IR graph grows too large (which it will if you don't mark step), the process will crash with HBM OOM.

Compile the graph means, the IR graph which is a DAG of pytorch ops, is taken and transformed to a graph that TPU can understand and execute. This transformation is costly, so ideally we see a constant number of different graphs in a workload, and subsequent calls to an already seen graph is just a cache lookup, which is cheap.

**Comment by mli** [comment]
@taylanbil is it possible to add `mark_step` to the functions that need the actual value such as `float` and `.cpu()`, so no need to call `mark_step` explicitly? Or there are other considerations not to do it.

**Comment by taylanbil** [comment]
https://github.com/pytorch/xla/pull/2770 tries that, but unfortunately it's blocked by pytorch `view`'s as explained in https://github.com/pytorch/xla/pull/2770#issuecomment-780092708
