### ISSUE TITLE
TorchScript and XLA

### ISSUE THREAD

**Issue by alexwong** [pytorch/xla#2806]
## ❓ Questions and Help
I thought when referring to PyTorch's IR, it is commonly interchanged with TorchScript and we run torch.jit.trace/script on a model and from the ScriptModule, we can get the graph which is essentially the IR. It seems like the integration here with XLA doesn't use that? How does pytorch/xla partition the graph and translate ops to HLO? Are there differences when converting forward and backward passes (cause it seems like one of the main use-cases is training)?

**Comment by ailzhang** [comment]
Pytorch/xla integrates to pytorch eager mode by implementing aten op kernels like CPU and CUDA. It construct its HLO graph by translating aten op to HLC when it's called (note the graph is not executed). 
Torchscript IR is mostly interchanged with aten ops but since scripting looks at ast you'll get IR node for control flow in torchscript graph which doesn't exist in pytorch/xla graph. 
pytorch/xla graph looks more similar to a jit.trace graph with some minor differences:
1. It's already HLO IR instead of aten IR in jit traced graph
2. it's automatically generated as you run eager PyTorch code while jit.trace need an explicit call with explicit input tensor shape. 

Pytorch/xla is designed as an eager backend for PyTorch just like CPU/CUDA, although it uses graph techniques under the hood, it should be hidden from users. In other words, pytorch/xla uses eager mode autograd system from pytorch and if we had an aten level IR forward/backward graph, it'll look exactly the same as how CPU/CUDA are executed. 

Torchscript/tracing when comes to backward passes uses https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/symbolic_script.cpp to generate DifferentiableSubgraph in backward graph. It's slightly different from eager mode autograd in certain ops but they're similar in functionality (apply differentiation formula).

**Comment by alexwong** [comment]
I see, thank you. I see this PR https://github.com/pytorch/xla/pull/1940/files for an example of adding a new op lowering. But I'm unsure how we go from PyTorch to pytorch/xla still. For the training case, it seems everything happens at runtime and the user only has to define input tensors with the xla device parameter and call xm.mark_step() at the end of each iteration of the training loop. 

Could you point me to the code where pytorch/xla walks through the existing pytorch backwards graph and constructs each of the new ops? I see https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp is the op-level interface between PyTorch and pytorch/xla but what orchestrates that (like a parser)?

**Comment by byronyi** [comment]
http://blog.ezyang.com/2020/09/lets-talk-about-the-pytorch-dispatcher/
