### ISSUE TITLE
xm.get_xla_supported_devices("TPU") hangs when no TPU is available.

### ISSUE THREAD

**Issue by tchaton** [pytorch/xla#2851]
## To Reproduce

To reproduce the bug:

```
export TPU_IP_ADDRESS=X.X.X.X
export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
```

Don't connect a TPU instance.

Run python:
```
import torch_xla.core.xla_model as xm
xm.get_xla_supported_devices("TPU")
```

As environment variable are set but no TPU is available and no timeout, the call will hang. 

1.
2.
3.

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:

**Comment by JackCaoG** [comment]
This is a expect behavior, when exporting `XRT_TPU_CONFIG` with a remote `TPU_IP_ADDRESS`, it will try to connect to the tf server at that IP address. If that IP is not reachable, it will hang for a while.

I am still a bit unsure what you want to do here. Are you still trying to check if it is a tpu use case? The problem here is that the vm that you are running on is just a regualr vm. The TPU lives in a remote vm with the `TPU_IP_ADDRESS`.
