### ISSUE TITLE
Floor division

### ISSUE THREAD

**Issue by ZhaofengWu** [pytorch/xla#2946]
I'm very new to xla, but what's the best way to do floor division of an s32 tensor by a scalar integer and expect another s32 tensor? `//` or `torch.floor_division` seem to trigger a re-compilation. `torch.div(a, b, rounding_mode="floor")` yields an f64 tensor in the IR even though the result is actually a torch.int tensor in pytorch. I also tried to explicitly do `torch.div(a, b, rounding_mode="floor").to(torch.int)`, but it doesn't seem to make a difference: the IR stops at `aten::floor` without any cast in it.
```
   ...
  %3572 = f32[64,2]{1,0} xla::cast(%3571.1), type=f32, dtype=Float
  %3573 = f32[64,2]{1,0} aten::div(%3572, %1)
  %3574 = f32[64,2]{1,0} aten::floor(%3573), ROOT=0
}
```

Environment: Google Cloud torch-xla-1.8.1

**Comment by JackCaoG** [comment]
Yea.. it is from 
https://github.com/pytorch/xla/blob/af0e2ef4b8220ee87f556ec6e4cacf5e7a54f3cf/torch_xla/csrc/tensor_methods.cpp#L1123

Torch `div` once default all divide to `true divide`(still the case if `rounding_mode` is not specified) so I converted `input` and `other` to floating IR. I guess for floor division we don't need to do that since floor is the default behavior of int division. Let me see if I can fix it easily.

In the mean time, IR type doesn't always 1:1 map to pytorch type. `to(torch.int)` doesn't do anything because pytorch dtype is already `torch.int`. One ugly workaround could be `.to(torch.float32).to(torch.int32)`. Let me fix the unnecessary cast to float for two int type for floor division through.

**Comment by JackCaoG** [comment]
Actually we do need to cast to floating point when we perform the floor divide. If we don't cast, for things like `-1 // 10` will return 0 instead of -1 for pt/xla. Maybe I should cast the IR to corresponding pytorch dtype to resolve this mistach in pytorch dtype and IR type.
