### ISSUE TITLE
[PT_BREAK] Structured kernels

### ISSUE THREAD

**Issue by ezyang** [pytorch/xla#3016]
Most of the diffs in https://github.com/pytorch/pytorch/pull/60817 stack need XLA changes. I think it applies to any diff that affects a Scalar overload.

cc @Freey0

**Comment by JackCaoG** [comment]
I replied in https://github.com/pytorch/pytorch/pull/60813#issuecomment-870830872, want to understand whether type promotion of boolean to byte is intenional.

**Comment by JackCaoG** [comment]
Updated https://github.com/pytorch/pytorch/pull/60811#issuecomment-871740423, seems like something we should fix in the pytorch side.

**Comment by JackCaoG** [comment]
Regarding Ed's comment in https://github.com/pytorch/pytorch/pull/60811#issuecomment-871859505, in fact pt/xla already handles binary OP between XLA tensor with CPU tensor through [this function](https://github.com/pytorch/xla/blob/f735104319c5ab264acf25a3c2bbfde9f7567ada/torch_xla/csrc/aten_xla_type.cpp#L115). In https://github.com/pytorch/xla/pull/1757 we even supported (`CPU tensor` op `XLA tensor`). I believe in cuda this is only valid if `CPU tensor` is a 0 dim tensor but we decided we won't check `CPU tensor` dimension in this case. I will extend this to bitwise* ops.

It seems like pytorch now will wrap scalar in a CPU tensor and pass it to the pt/xla for structured ops. Pt/xla handles CPU tensor and scalar differently. For Cpu tensor, we will create a `XLATensor` with a `IrValue`. For scalar, we will only create a `IrValue` and use it as the input to the result tensor IR. By alway passing scalar as a wrapped CPU tensor, pt/xla will pay the cost of creating a XLATensor and deleting it when wrapped scalar tensor go out of the scope. I think speed wise this should be fine since we will need to do a scalar upload to XRT either way, the additional cost was just registering and deregistering the XlaTensor.

**Comment by ezyang** [comment]
@JackCaoG Yes I agree it's a bit awkward. It would be really nice to have some better strategy for scalars; right now wrapping scalar in CPU tensor helps reduce the number of functions backend has to implement, but at the cost of more framework overhead. I don't really want to ask people to implement ALL the scalar overloads for all functions either...

**Comment by JackCaoG** [comment]
Close this issue as pytorch and pt/xla are both merged.
