### ISSUE TITLE
Lowering for aten::as_strided

### ISSUE THREAD

**Issue by ultrons** [pytorch/xla#3020]
aten::as_strided lowering is Needed to support atom3d enn training of LBA dataset.

**Comment by JackCaoG** [comment]
as_stride is already lowered https://github.com/pytorch/xla/blob/74168789dfad6834a359ccb25c5bdf09ae58f9f8/torch_xla/csrc/aten_xla_type.cpp#L607, there are some cases that it can not handle through

cpu and gpu have storage and hence it can do stride with share memory. XLA does not have storage so we usually fake it with some reshape. There are some cases that we can't support due to this limiation. It will be better you can identify where the `as_stride` is coming form and what kind of stride it is trying to apply
