### ISSUE TITLE
Monitoring TPU-VM

### ISSUE THREAD

**Issue by kat25230** [pytorch/xla#3157]
## ❓ Questions and Help
Hi Pytorch XLA team,

I'm training a pytorch model on a TPU-VM based on this [tutorial](https://cloud.google.com/tpu/docs/pytorch-quickstart-tpu-vm#tpu-vm_2). 
I would like to monitor the performance of the TPU MXU, but when looking at the code base I only found trace functions see [here](https://github.com/pytorch/xla/blob/master/torch_xla/debug/profiler.py).

I was wondering if there is some support for monitoring like this [function in TF](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/profiler/profiler_client.py#L135).

Or if there is some other way to monitor TPU performance in PyTorch-XLA.

Thanks in advance!

**Comment by jysohn23** [comment]
Yeah we don't currently have that, but it should be pretty easy to add that API to PyTorch/XLA since we use the same underlying instrumentation.

Similar to this
https://github.com/pytorch/xla/blob/457270c2466b47ee15248f7dbac54915d26beca2/torch_xla/csrc/init_python_bindings.cpp#L676

You can add a binding that calls `monitor` instead: https://github.com/tensorflow/tensorflow/blob/ef594f97fb97bbaf268b034b159518fa50e7db9d/tensorflow/python/profiler/internal/profiler_wrapper.cc#L118
