### ISSUE TITLE
slow compiling

### ISSUE THREAD

**Issue by sipie800** [pytorch/xla#3336]
I am using xla on google colab tpu.
I am editting model and testing.
Everytime I've edited model , I just need one time testing run.
Thought I just add a simple nn.ReLu and re-run. Xla compile again and took more than 5min to begin training.
It drives a researcher mad. We want to edit and run without a weird waiting. Please consider to make xla better.

**Comment by JackCaoG** [comment]
Thanks for reporting. The slow compile is due to the nature of the xla compiler. Optimizing a graph takes time and we expect user to compile a graph and run it many times to take advantage of the faster step time.

That being said, if all you need is an okish speed and you know you need to constantly change the graph, consider using the `opbyop` mode. You can check [this doc](https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#more-debugging-tools) and export `XLA_GET_TENSORS_OPBYOP =1 XLA_SYNC_TENSORS_OPBYOP=1`. Compilation will be very fast but execution will take longer(unoptimized).
