### ISSUE TITLE
XMP spawn problem on TPU VM

### ISSUE THREAD

**Issue by Longman-Stan** [pytorch/xla#3716]
## 🐛 Bug

I've tried training a huggingface transformer on a Google TPU VM machine to no avail. Upon debugging, I've observed that the spawning process hangs, without printing any error for some time. 

After a while, it prints a long error message, most important being (I guess) "Failed to connect to client mesh master: t1v-n-5db23080-w-0.us-central1-a.c.upbeat-voice-346114.internal:58799".

I have set everything according to https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm , including `export XRT_TPU_CONFIG="localservice;0;localhost:51011"`.

Interestingly, I can run test_train_mp_imagenet.py just fine, but my dummy code exhibits the problem above.
## To Reproduce

1. Open a TPU VM: gcloud compute tpus tpu-vm create distilgpt --zone=us-central1-a --accelerator-type=v3-8 --version=v2-alpha
2. Run the script:
```
import torch_xla.distributed.xla_multiprocessing as xmp

def _mp_fn2(index):
    print(f"Hello! {index}")

xmp.spawn(_mp_fn2, args=(), nprocs=8)
```

## Expected behavior
Print 8 "Hello! x", permuted messages.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU VM
 - torch_xla version: 1.8.1

## Additional context

[Error stack.txt](https://github.com/pytorch/xla/files/9115480/Error.stack.txt)

**Comment by JackCaoG** [comment]
this has to do with how mesh_server works. Short answer is that master process is in charge of getting the mesh from TPU and then distributed to other process. In your example master process exit immediately after it acquire the whole mesh because in the `mp_fn` you defined it does not have any real operations. This leaves other process waiting for the mesh forever and failed.

To make your example work, add 
```
import torch_xla.core.xla_model as xm

def _mp_fn2(index):
   print ('lalala')
   xm.rendezvous("test")
```

should work, This should force master process wait until all process reach `rendezvous` before exiting. Or you can just add some real pytorch op and all_reduce to force the master process wait for other process to come up.

**Comment by Longman-Stan** [comment]
Thank you for the clarifications!
