### ISSUE TITLE
High level interface for interaction with the XLA client

### ISSUE THREAD

**Issue by carmocca** [pytorch/xla#4897]
## 🚀 Feature

Jax provides some neat useful utilities
```python
jax.default_backend()
jax.device_count()
jax.devices()
jax.host_count()
jax.host_id()
jax.host_ids()
jax.local_device_count()
jax.local_devices()
jax.process_count()
jax.process_index()
```

These are defined in https://github.com/google/jax/blob/main/jax/_src/xla_bridge.py
Which uses their library `jaxlib`: https://github.com/google/jax/tree/main/jaxlib
To interact with the `xla_client`: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/xla_client.py

## Motivation

Torch XLA currently defines some of the utilities above in `torch_xla.core.xla_model`, but not all.

Also having access to directly to the XLA client could be useful

## Pitch

Expose all these 

## Alternatives

I saw that Torch XLA loads `libtpu`, but couldn't find any link from this to the TF XLA client python frontend

## Additional context

This would simplify how Lightning gets this information. I'm particularly interested in `device_count()` as we need to launch a separate process to call `len(xm.get_xla_supported_devices("TPU"))`. It doesn't seem like jaxlib has these usability issues.
https://github.com/Lightning-AI/lightning/blob/50662eb0781fdb7184f5958736847955558874b0/src/lightning/fabric/accelerators/tpu.py#L90-L134

**Comment by JackCaoG** [comment]
@will-cromar I think we should have most of above utilities available, can you confirm?

**Comment by will-cromar** [comment]
Almost all of these already have equivalents in PyTorch/XLA already, mainly in [`torch_xla.experimental.pjrt`](https://github.com/pytorch/xla/blob/master/torch_xla/experimental/pjrt.py). A subset are in `xm.xla_model` too. 

- jax.default_backend() -> pjrt.device_type() (PT/XLA+PJRT only has one XLA backend at a time, unlike JAX)
- jax.device_count() -> pjrt.global_device_count()
- jax.host_id() / jax.process_index() (these are identical AFAIK) -> pjrt.process_index()
- jax.local_device_count() -> pjrt.addressable_device_count() (or pjrt.local_device_count() to include devices in other processes on the same host)
- jax.local_devices() -> xm.get_xla_supported_devices()
- jax.process_count() -> pjrt.process_count()

These are mostly calling the same PJRT APIs as JAX too. We're only missing `jax.devices()` and `jax.host_ids()` out of that list. I'm not sure `jax.devices` makes sense for us, because we don't have a Python representation of a device outside of the local process anywhere else. If you have a use case for these two, can you tell use more about how you plan to use them?

For getting the number of available devices without instantiating a PJRT client, you're in luck. I just sent https://github.com/pytorch/xla/pull/4927, which returns the number of XLA TPU devices visible on the current host. If it's useful, we can add a more uniform API that works for GPU and CPU too.

The main functional difference between our usage of PJRT and jaxlib's is that they generally create one process per TPU host and use SPMD to distribute computations between addressable devices. We create a separate process per TPU chip. Unfortunately, due to low-level constraints, only one process can open the TPU device at a time, so if you initialize the TPU runtime in the parent process with e.g. (`len(xm.get_xla_supported_devices("TPU"))`), it excludes the child subprocesses from opening their assigned TPU chip. Basically, you can't actually directly use the TPU or runtime before calling `xmp.spawn`.

**Comment by JackCaoG** [comment]
@carmocca does this answer your question?

**Comment by carmocca** [comment]
Yes. This was super helpful. Thanks to both of you!

**Comment by carmocca** [comment]
> If it's useful, we can add a more uniform API that works for GPU and CPU too.

It would be. For CUDA GPU support with XLA, is it expected that users would go through `torch.cuda` for these checks or does XLA plan to expose this via `torch_xla.experimental.gpu`?

**Comment by will-cromar** [comment]
Right now, users are expected to set `GPU_NUM_DEVICES` themselves. This behavior is carried over from XRT, but I'm not a fan of making users set a bunch of configuration themselves in the default case.

I'm planning a broader redesign of the way we handle devices to better support new hardware implemented through the PJRT Device API (e.g. XPU). I'll make sure a safe way to get the expected number of devices is part of that design.

For this simple case, I can add something like `pjrt.expected_num_devices` in the next week or two.
