### ISSUE TITLE
Op lowering for AtenAvgPool2dBackward

### ISSUE THREAD

**Issue by danielvegamyhre** [pytorch/xla#5773]
In #5764 AtenAvgPool2dBackward is listed as an op that needs to be lowered in XLA. This issue is to track the work on lowering this op.

**Comment by danielvegamyhre** [comment]
@JackCaoG quick question, I'm on step 3 in the lowering guide, implementing the missing IR function: https://github.com/pytorch/xla/blob/master/CODEGEN_MIGRATION_GUIDE.md#3-implement-the-missing-ir-function

However, it says we should not implement it from scratch, but rather reference the XLA::Shape computation logic from the existing op: `"Note that you should not start from scratch. Find the Xla::Shape computation logic from the existing op and move it this these two files."`

Does this mean to find existing output shape computation logic in `aten/` in PyTorch itself? Or it should exist somewhere in pytorch/xla already? I haven't been able to find it in either location yet, the closest I've found is this `avg_pool2d` function [here](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/lowering.py#L4106).

**Comment by JackCaoG** [comment]
@wonjoolee95 @lsy323 can you guys help?

**Comment by wonjoolee95** [comment]
Hey @danielvegamyhre, thanks for working on this!

So the guide you're looking at is the `CODEGEN_MIGRATION_GUIDE`, which is our guide the migrate an existing lowered op to codegen (FYI codegen is just a mechanism to generate all the boilerplate files/functions/etc to make op lowering easier). In this case, `AtenAvgPool2dBackward` is not lowered yet, so that "Note that you should not start from scratch" does not apply -- we'll need to implement the shape function by ourselves. Let me know if you have any more questions anytime.

**Comment by miladm** [comment]
@wonjoolee95 how is this lowering different from [this one](https://github.com/pytorch/xla/blob/b8b8ea8685bf0f881471c6782f37dbbcf05e9fc7/codegen/xla_native_functions.yaml#L144)?

**Comment by danielvegamyhre** [comment]
As miladm@ mentioned, this op is already listed in the `supported` section of xla_native_functions.yaml, so as far as I can tell it has been lowered already. I'll close this issue now, but if I'm mistaken about something please feel free to re-open.
