### ISSUE TITLE
How to add a new third-party Backend

### ISSUE THREAD

**Issue by dinghaodhd** [pytorch/xla#6014]
## ❓ Questions and Help
1 We see PyTorch/XLA now pulls XLA from OpenXLA, is that means we just need to adapt OpenXLA to add a new backend?
2 Will collective operations work with third-party backend?

**Comment by JackCaoG** [comment]
Perfect question for @will-cromar 😄

**Comment by bmeoaountiful** [comment]
For Q1, pytorch-xla also needs to be adapted.I'm also interested in Q2. What needs to be done for the new third-party backend regarding spmd and fsdp?

**Comment by mmseerrttt** [comment]
For Q1, pytorch-xla also needs to be adapted.I'm also interested in Q2. What needs to be done for the new third-party backend regarding spmd and fsdp?

**Comment by will-cromar** [comment]
You're reaching out at a good time, since I'm getting back to working on this topic. The upshot is, to add a new device backend, you have to implement the PJRT C API, which wraps your custom compiler and runtime. There are links to some resources over in the [OpenXLA repo](https://github.com/openxla/xla/tree/main/xla/pjrt/c). We actually use the PJRT C API for TPU now, so all functionality such as collectives, FSDP, SPMD, etc will work with custom backends as well (assuming all relevant ops are implemented in your runtime). I'm also working on converting our XLA GPU backend to use the PJRT C API.

To actually add a new backend today, you would need to make a PR like #5428 that registers the device type in several places. This is pretty clunky, so I'm working on a dynamic registration API for plugins in #5644 that will allow you to distribute your backend in a separate package without having to adapt PyTorch/XLA.

**Comment by will-cromar** [comment]
I started a tracking issue for improving custom backend support at #6242. Let's move any further discussion there.
