### ISSUE TITLE
How to choose XRT runtime when using Torch/XLA 2.1.0?

### ISSUE THREAD

**Issue by andrey-klochkov-liftoff** [pytorch/xla#6331]
The PJRT docs say that setting `XRT_TPU_CONFIG` would choose the XRT runtime, but even when I set it I see the following warnings in the logs, and PJRT gets enabled. My model trains faster on XRT but I'd like to upgrade to 2.1.0. Thanks!

```
WARNING:root:PJRT is now the default runtime. For more information, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
```

**Comment by JackCaoG** [comment]
XRT Runtime only exist in a special whl, you can see more detail in https://github.com/pytorch/xla#python-packages. I think this is what you want
```
https://storage.googleapis.com/pytorch-xla-releases/wheels/xrt/tpuvm/torch_xla-2.1.0%2Bxrt-cp310-cp310-manylinux_2_28_x86_64.whl
```

**Comment by andrey-klochkov-liftoff** [comment]
Thank you, that worked!

**Comment by JackCaoG** [comment]
SG! XRT is deprecated after 2.1 release. One common issue we saw people complain about torch_xla 2.1 is slower is due to functionization. If you do `XLA_DISABLE_FUNCTIONALIZATION=1` with `torch_xla` 2.1, I would be very surprise. I will close this issue for now, feel free to reopen if you have any follow up items.
