### ISSUE TITLE
torch.distributed.checkpoint and XLA backend

### ISSUE THREAD

**Issue by wintwoo** [pytorch/xla#6465]
Referring to the "SPMD user guide" here: https://github.com/pytorch/xla/blob/535d398b9a7d2952d04abe6395307897352664d2/docs/spmd.md

What's the right approach to use the `torch.distributed.checkpoint` (and the distributed checkpoint manager) on Cloud TPUs?

I understand I should call `init_process_group` to use the `torch.distributed.*` functions. When I use:

```
xr.use_spmd()
dist.init_process_group("xla", init_method="pjrt://")
```

I run into this broken assertion: `AssertionError: XLA backend is not supported with SPMD. Please use a CPU process group instead.`

Do I need to init a CPU process group (with rank, world size etc) in "parallel" with how I normally use `torch_xla.core.xla_model` for distribution on TPUs?

**Comment by JackCaoG** [comment]
@jonb377 can you help? Let's also use this chance to update the user guide if needed.

**Comment by jonb377** [comment]
In SPMD mode, we currently don't allow a process group to control the on-device collectives, since all collectives are inserted by the compiler. However, distributed checkpointing requires a process group to coordinate the checkpoint.

The current recommendation is to use a CPU process group such as `gloo`. The `xla://` init_method is still supported for master IP discovery on TPUs. Your example should work with:

```python
xr.use_spmd()
dist.init_process_group('gloo', init_method='xla://')
```

I missed this in the documentation, I'll add an example of `init_process_group` to the CheckpointManager section.

**Comment by wintwoo** [comment]
Thank you for the clarification!

**Comment by ManfeiBai** [comment]
Hi, Thanks, @wintwoo, does above helped answer all questions?

If yes, I would suggest to mark this issue as fixed; or let's continue discuss for follow-up questions
