### ISSUE TITLE
Loading large sharded model weights

### ISSUE THREAD

**Issue by adithyaiyer1999** [pytorch/xla#6989]
## ❓ Questions and Help

Hi!

I'm trying to enable checkpointing of our training runs, which involves saving the model weights, and the optimzer states, and then when i want to continue from the last checkpoint - load both into the model.

My problem is - if the model is really big, loading the entire model and opt state is impossible due to memory contraints (on v4 tpus) - so I am attempting to load my sharded models. 

The way i save the model weights, inside each worker/processis as follows :

```
# ckpt_path is path name saved with a string with a number inidicating which process 
state_dict = self.model.state_dict()
        cpu_state_dict = {
                key: value.cpu()
                for key, value in state_dict.items()
            }
os.makedirs(os.path.dirname(ckpt_path), exist_ok=True)
xm.save(ckpt, ckpt_path, master_only=False)
```

This creates say 8 separate model shards for say a TPU-v4-16. When i load back, I'm trying to use:

```
state_dict = torch.load(path)
state_dict = state_dict["model"]
xm.send_cpu_data_to_device(state_dict, xm.xla_device())
self.model.load_state_dict(state_dict)
```

Im mostly referring to https://github.com/pytorch/xla/blob/master/docs/fsdp.md , but even here, the load -> then shard. I want to directly load sharded weights into each process. Currently, Im running into the following error when i do model.forward:
```
indices should be either on cpu or on the same device as the indexed tensor (XLA). When using XLA, the indexed tensor must be an XLA tensor.
```

Essentially, although my model weights are xla tensors, the maybe seem to be in the wrong device? i've verified that everything is in xla device, although when i print `xm.xla_device()`, it always shows `xla:0` (this makes sense because each process can only see it's device).

Any best practices on loading from shards for really large models?

Thanks!

**Comment by JackCaoG** [comment]
You seems to be using FSDP, @jonb377 @alanwaketan any experience you can share for loading the sharded weights?

**Comment by jonb377** [comment]
Gerson has proposed loading the model layer-by-layer to limit host memory usage: https://github.com/pytorch/xla/issues/6822#issuecomment-2021286687

I'm not sure how the optimizer is handled for FSDPv1 checkpoints though, @gkroiz any thoughts?

**Comment by gkroiz** [comment]
@adithyaiyer1999 to fix the error you are seeing when loading a sharded checkpoint, could you try the following in order(if you haven't tried already):
1) make sure that each rank loads the right checkpoint (i.e, rank 4 should load the checkpoint that was saved by rank 4).
2) shard the model via FSDP before loading sharded weights,
3) remove `xm.send_cpu_data_to_device(state_dict, xm.xla_device())` before `load_state_dict` and let `load_state_dict` deal with transferring tensors to the correct device.

Regarding how to minimize memory consumption when loading checkpoints, the comment @jonb377 linked is a good reference. For minimizing memory consumption when loading the optimizer state, maybe instead of loading in data layer-by-layer, you could load in data sequentially where you iterate over optimizer parameters.

**Comment by adithyaiyer1999** [comment]
Hi!

Thanks a lot, removing `send_cpu_data_to_device`  from all locations, and not moving any weights to CPU worked for me.

Adithya
