### ISSUE TITLE
`is_master_ordinal` breaks dataloader

### ISSUE THREAD

**Issue by Jiayi-Pan** [pytorch/xla#7074]
## To Reproduce
We've localized this bug in a minimal codebase here: https://github.com/Jiayi-Pan/xla_minimal_bug/tree/main

Please follow the readme to reproduce the bugs on a multi-gpu machine.

Basically, in a multi-gpu setting, any data loader with a naive worker_init_fn fails if we call `xm.is_master_ordinal()` in a global context.

## Expected behavior

Checking `xm.is_master_ordinal()` shouldn't break the MpDeviceLoader
However, the dataloader actually failed when we do so

## Environment

 - Reproducible on XLA backend [CPU/TPU/CUDA]: CUDA
 - torch_xla version: 2.3

**Comment by JackCaoG** [comment]
@vanbasten23 any idea on this one?

**Comment by vanbasten23** [comment]
Taking a look. You should be able to call is_master_ordinal as in our example https://github.com/pytorch/xla/blob/8247aec1aea293ff1a60f0eae358306c935d2656/test/test_train_mp_imagenet.py#L268 and we invoke the script via
```
+ PJRT_DEVICE=CUDA
+ GPU_NUM_DEVICES=2
+ python3 test/test_train_mp_imagenet.py --fake_data --batch_size=16 --num_epochs=1 --num_steps=25 --model=resnet18
```

**Comment by Jiayi-Pan** [comment]
Hi @vanbasten23, thanks for suggestion! But we really need the structure illustrated in our minimal bug example for certain reason in our actual codebase.
Do you have any idea why xla fails in this particular case?

**Comment by vanbasten23** [comment]
I commented out the `xm.is_master_ordinal()` in your global context and still see the exception https://gist.github.com/vanbasten23/c8df1fae91cd556f80b2034adabc3f55 from data loader

**Comment by vanbasten23** [comment]
There a few changes I think you need to make. I modified your repro https://github.com/Jiayi-Pan/xla_minimal_bug/compare/main...vanbasten23:xla_minimal_bug:xiowei/debug?expand=1 and it works with `PJRT_DEVICE=CUDA GPU_NUM_DEVICES=2 python xla_entry.py`.

1. You don't need `dist.init_process_group` and the `dist.barrier()` per our example
2. Another issue is you used `worker_init_fn` in `torch.utils.data.DataLoader`. I also remove it to make it work. Do you need the `worker_init_fn` or it is not necessary.

I modified our example pytorch/xla/test/test_train_mp_mnist.py to match your use case https://github.com/pytorch/xla/compare/xiowei/debugIssue7074?expand=1 and verified it runs ok. So it seems to me `xm.is_master_ordinal()` is not the problem.

**Comment by Jiayi-Pan** [comment]
Hi, thanks for the help!
I just reproduced the error in a new clean xla environment (pytorch 2.3 w/ cuda), but in my case, removing ` if xm.is_master_ordinal():` indeed makes this work. Is there any environment status log that I can report to you so that we know what's going wrong?
Unfortunately, we do need `worker_init_fn` in the actual codebase. It's just a simplied version where we find even an empty function will cause the error.

**Comment by vanbasten23** [comment]
I think what happens is when you run the script `PJRT_DEVICE=CUDA GPU_NUM_DEVICES=2 python xla_entry.py`
1. torch_xla spawn 2 processes
2. each process runs your function `xla_train` which initialize a GPU client. At this point, everything is expected.
3. Then when you do `for data, target in dataloader:`, each process spawn another 2 subprocess (4 subprocesses in total, because `num_workers=2` is specified in `DataLoader`)
4. After the subprocess is start, each subprocess import the `main` module in order to load the `worker_init_fn` ([log](https://gist.github.com/vanbasten23/83f24c181e054617f5fb01d3eb1caa85) you can see each subprocess import the `main` and subsequently call `xm.is_master_ordinal()` which initialize the runtime) because your `worker_init_fn` is defined at the top level of the module.
5. Then each subprocess tries to create a new GPU client and that's where it fails.

For torch_xla, each subprocess should not create a GPU client and it is something we don't support. As a workaround, could you try to put your `worker_init_fn` (ie `def naive_worker_init_fn(worker_id: int) -> None:`) to a different module other than `main`? 

cc @will-cromar @JackCaoG

**Comment by Jiayi-Pan** [comment]
thanks! this solved my issue
