### ISSUE TITLE
Distributed Checkpointing Saving Empty Files with 2D SPMD

### ISSUE THREAD

**Issue by huzama** [pytorch/xla#7118]
### Issue Summary

When sharding the model using the 2D SPMD strategy, the checkpointing code saves all the data from rank 0, but creates empty files for other ranks. However, when using 1D Sharding with FSDPv2, the checkpointing works correctly.

### To Reproduce

1. Apply 2D SPMD sharding on model parameters.

2. Try to save the checkpoint using the `CheckpointManager` as shown in the code snippet.

```python

for param in model.parameters():

    if param.ndimension() == 2:

        xs.mark_sharding(param, spmd_mesh, ("model", None))

        

chkpt_mgr = CheckpointManager('path', 10)

chkpt_mgr.save(step, model.state_dict())

```

### Expected Behavior

Checkpointing with 2D SPMD should save the data correctly from all ranks, just like it does with 1D Sharding using FSDPv2.

### Environment

- **Backend used (CPU/TPU/CUDA):** TPU

- **torch_xla version:** 2.3

- **torch version:** 2.3

- **TPU configuration:** v4-256 pod

- **Save directory:** Google Cloud Storage Bucket

**Comment by JackCaoG** [comment]
hmm @jonb377 any idea?

**Comment by jonb377** [comment]
Hi @huzama, could you please share details on the mesh shape?

This could be explained by partial replication of the model parameters. When multiple devices host the same data (e.g. it's replicated on devices 0 and 4), only replica 0 will write to the checkpoint. 

It seems in this case the entire model is being replicated across any non-`model` mesh axes due to `xs.mark_sharding(param, spmd_mesh, ("model", None))`, so only a subset of workers will participate in the checkpoint.

Here is where writes are deduplicated in the checkpoint planner: https://github.com/pytorch/xla/blob/1a8c2fe25383abcf8a2be483112e8579d7d65edb/torch_xla/experimental/distributed_checkpoint/planners.py#L109-L110

I believe we could make this a bit more optimal by distributing the writes across replicas instead of having the rank-0 replica do all the writing.

**Comment by huzama** [comment]
Thank you @jonb377,

My initial mesh shape was (4: 'model', 32:' data'). However, I updated it to `xs.mark_sharding(param, spmd_mesh, ("model", "data"))` to utilize 2D sharding instead of row-wise sharding, which resolved the issue. Now, I am able to save data from all machines.

Additionally, I have observed that the gscfs extension is significantly slower when copying files to the cloud compared to using the command `gcloud alpha storage cp -r {temp_path} {cloud_path}.` It would be great if we could incorporate a faster method.

**Comment by jonb377** [comment]
Thanks @huzama, glad that fixed it! I've also experienced the slowdown with gcsfs, I believe it primarily comes from the upstream FsspecWriter being single-threaded when processing and writing the tensors. You can try using async checkpointing to hide the latency with `save_async`, but this will still block subsequent checkpoints if the writes are too slow.


I see the upstream is adding [thread_count](https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/_fsspec_filesystem.py#L95) support, which would speed things up significantly. Unfortunately, from a quick test this isn't working yet for fsspec backends.
