### ISSUE TITLE
Op info test for `__rpow__`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7387]
## Fix the Op info test for `__rpow__`

1. Find the line 14 of [test_ops.py](test/test_ops.py) and remove
   `__rpow__` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
Hi, @nupurbaghel, thanks for contribution! This issue would be one of the first issue, please feel free to reply this issue, so that we could assign it to you

**Comment by nupurbaghel** [comment]
Thanks @ManfeiBai happy to take up this issue.

**Comment by nupurbaghel** [comment]
- rpow is used by Pytorch to raise a scalar to tensor powers. The aten pow operator already implements both pow and rpow functionalities using jnp.power. 
- The test for rpow cannot be removed from the skip list because of known inconsistencies between results of NumPy and PyTorch such as raising 0 to negative powers. [#121926](https://github.com/pytorch/pytorch/issues/121926)

**Comment by ManfeiBai** [comment]
thanks for the investigation, let's close this ticket

**Comment by ManfeiBai** [comment]
> thanks for the investigation, let's create a new skip list(`unsupported numrical calculation false`) for op like this: https://github.com/pytorch/xla/blob/e657c87212149d07217f056ac9a03173bc779c9d/experimental/torch_xla2/test/test_ops.py#L178C1-L192C2

mentioned in the skip list
