### ISSUE TITLE
Op info test for `linalg.eig`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7479]
## Fix the Op info test for `linalg.eig`

1. Find the line 114 of [test_ops.py](test/test_ops.py) and remove
   `linalg.eig` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
Hi, @shitongWang, thanks for the contribution, this issue would be part of the second issues to try, please feel free to comment, so that we could assign this ticket to you

**Comment by ManfeiBai** [comment]
Hi, @anishfish2, thanks for your contribution! this is one of the second 5 ops issues, and please feel free to reply this issue, so that we could assign this to you

**Comment by anishfish2** [comment]
Claiming this issue!

**Comment by ManfeiBai** [comment]
synced offline, due to jnp and torch complex64 and complex128 difference, would suggest to specific atol/rtol used to comfirm difference of `linalg.eig` from torchxla2 and jax, like https://github.com/pytorch/xla/blob/d79a37c408301bf7f845c74e32e0c973138fdbeb/experimental/torch_xla2/test/test_ops.py#L198C1-L198C69

**Comment by anishfish2** [comment]
Sounds good, I'll try this!
