### ISSUE TITLE
Input tensor is not an XLA tensor: torch.LongTensor

### ISSUE THREAD

**Issue by Crysitna** [pytorch/xla#899]
I was following the mnist example, transferring the original pytorch code into xla framework, the code is roughly like this: 
```Prebuilt Compute VM Images
model = Model(xxx)
devices = xm.get_xla_supported_devices(max_devices=8)
c= dp.DataParallel(model, device_ids=devices)

model_parallel(train_loop_fn, datagen)
```
where the `datagen` is an instance of `torch.Dataloader()` generating 3 LongTensor and 1 FloatTensor each time, the four tensors are wrapped in a tuple. 

Yet inside `train_loop_fn`:
```
def train_loop_fn(model, loader, device, context): 
    model.train()
    for i, (a, b, c, d) in loader:
          model(a, b, c, d)            <----- reports error
```
it's reporting such type of error. I've compared the output of my dataloader and the mnist loader, it seems thery are mostly the same other than the tensor type (I'm generating a list of 4 tensors and they r generating a list of 2 tensors)... any suggestions on what's going wrong? Thanks!

-------------------
p.s I'm using the _Prebuilt Compute VM Images_ and the mnist example is able to run in this environment.

**Comment by ibeltagy** [comment]
I have seen this happening when the model is in tpu and the tensors are still in cpu. Can you print the device of each tesnor before calling your model? 
```
for i, (a, b, c, d) in loader:
         print(a.device, b.device, c.device, d.device)
          model(a, b, c, d) 
```

**Comment by Crysitna** [comment]
thanks! I guess the cpu tensor is the problem: tho the data generated by loader are located in xla devices, there r some tensors defined inside model are still located on cpu. After relocating them to corresponding devices the model works!

**Comment by tweetyone** [comment]
@Crysitna  How to relocate the tensor on cpu to xla device?

**Comment by ailzhang** [comment]
@tweetyone  `tensor.to(xla_device)` should do the job. example : https://github.com/pytorch/xla/blob/master/test/test_operations.py#L199

**Comment by dlibenzi** [comment]
The tensors returned by the `DataParallel` loader (the one you receive as argument to the loop function) should already be on an XLA device.

**Comment by dlibenzi** [comment]
I added this test: https://github.com/pytorch/xla/pull/941
If the data object returned by the loader is any nested combination of {list, tuple, dict, set}, it should work.
Can you print (recursively) the data of the object returned by your `dataloader_train`:

https://github.com/tweetyone/DCL/blob/0168bd97c1812dbbb59d4b6dc5a8c67077006f85/train_tpu.py#L199

**Comment by tweetyone** [comment]
> I added this test: #941
> If the data object returned by the loader is any nested combination of {list, tuple, dict, set}, it should work.
> Can you print (recursively) the data of the object returned by your `dataloader_train`:
> 
> https://github.com/tweetyone/DCL/blob/0168bd97c1812dbbb59d4b6dc5a8c67077006f85/train_tpu.py#L199

I found why the last 3 are not on xla device:
if I print dataloader_train at line 209 :   it is `(tensor([...]), [...], [...], [...])`
Maybe the reason why the last three are not on xla device is because they are not tensor at the beginning... But how to let them be tensors?

but I also found some strange things, when the dataloader transfer to the train loop, like if I print the data_loader value at line 122:  it is `(1, (tensor([...], device='xla:4'), [...], [...], [...]))`
I'm not sure why it add a number ...

And, during the training , I use 16v 60G cpu instance, I found the cpu usage of vm is very high (80%), while the cpu usage of tpu v3-8 node is less than 10%. Is the high vm cpu usage caused by the tensor relocation code?

**Comment by jysohn23** [comment]
> And, during the training , I use 16v 60G cpu instance, I found the cpu usage of vm is very high (80%), while the cpu usage of tpu v3-8 node is less than 10%. Is the high vm cpu usage caused by the tensor relocation code?

Per high CPU usage on the client VM side, the input pipeline is running all on the client VM which is CPU intensive. So if it's that high, it's likely you're VM CPU bottlenecked, so I'd suggest you try increasing the #CPU cores and increase the `num_workers` for the dataloader. So that's why you're seeing that high CPU usage. AFAIK, we don't run too much on the TPUs CPUs (no input pipeline bits) and instead just have tensor copying, passing to device etc.

**Comment by dlibenzi** [comment]
The `loader` you get within the loop function returns a tuple with:
```
(BATCH_NUMBER, (...))
```

When `...` is the data returned by the outer loader.
Did you implement the loader?
Usually loaders return tensors.

**Comment by rish-16** [comment]
Hey everyone,

Don't mind me jumping in here 😓  I received similar errors where the TPU instance crashes because my data is apparently a `FloatTensor` and not a `XLA Tensor`. I follow the similar steps prescribed in the `PT XLA MNIST on TPU` Colab notebook. 

As mentioned above, I added the `.to(xla_device)` to my dataloader tensors `x` and `y`. It still gave me the same error.

I describe my error: [#2960](https://github.com/pytorch/xla/issues/2960)

Any help appreciated! Thanks :)

**Comment by steveepreston** [comment]
facing this issue in 2024 on TPU VM env

```python
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.1-8B-Instruct", device_map="auto", torch_dtype="bfloat16",)
device = xm.xla_device()
model.to(device)

pipe = pipeline(task="text-generation", model=model, tokenizer=tokenizer, max_new_tokens=10, device_map="auto")
pipe("Hello!")
```
Throws this:

> Error:
> RuntimeError: torch_xla/csrc/aten_xla_bridge.cpp:105 : Check failed: xtensor 
> ...
>  Input tensor is not an XLA tensor: torch.LongTensor
