### ISSUE TITLE
Operations using aten::_local_scalar_dense()

### ISSUE THREAD

**Issue by Crysitna** [pytorch/xla#909]
it's somehow related to issue #836, I found the count of `aten::_local_scalar_dense`  is non-zero and even increasing during the training while there is no `.item()` or `clip_gradient` is used during training. wondering if there r other samples about the operation that would transfer the tensor to cpu?

p.s. not sure if it's related, the Compile Time also increases (a lot) during the training, and not in the same pace with the increase of `aten::_local_scalar_dense` counter, i.e. when the compile time increase, the `aten::_local_scalar_dense` counter may not change.

background: 
the experiemnts are on _pytorch-nightly_, and the shape of model input and output shape are constant each time. no dynamic loop during the training. and I removed all the _.item()_ call.

**Comment by taylanbil** [comment]
There are other calls that increase _local_scalar_dense. Off the top of my head, `.any()` does it for example.

**Comment by Crysitna** [comment]
thanks for the example. or maybe is there any way to list all/most of the common calls increasing the _local_scalar_dense? 
p.s. does the operation between a xla tensor and a scalar (e.g. `a = torch.sqrt(a + 1e-7)` shift `a` to cpu then back to tpu?

**Comment by Crysitna** [comment]
oh I just notice there r also some operator prefixed with `aten::`  in the IR graph: 
```
  %25 = pred[32,4,800]{2,1,0} aten::mul(%24, %19), location=forward@model.py:93
```
maybe does such operator indicate a transfer to cpu?

**Comment by dlibenzi** [comment]
No, almost all our IR nodes are named with the `aten::` prefix.
The local-scalar-dense happens every time the Python code switches from "tensor context" to "Python scalar context".

**Comment by Crysitna** [comment]
updates: 
I checked my code line by line and found 
1. `torch.nonzero()` would increase `aten::nonzero`
2. using xla tensor to indexing other tensors would increase `aten::_local_scalar_dense()`
e.g 
```
  device = ['xla1']
  a  = torch.tnesor(0).to(device) 
  b = torch.rand(20, 3)
  x = b[a]                          # aten::_local_scalar_dense() would increase
```

**Comment by dlibenzi** [comment]
Hi @Crysitna ,

`torch.nonzero()` is a bit of a problem for XLA, as it creates dynamic shapes.
Since within the current XLA implementation the shapes are static (and hence bolted in into the TPU compiled binary), every IR graph south of a `torch.nonzero()` will likely trigger a recompilation (and hence be pretty slow).
In certain cases you could be lucky, and the shapes variations coming out of a `torch.nonzero()` will be a limited set, so recompilations will stop at a given point.

If it gets too slow, you can try:
```Shell
export GET_TENSORS_OPBYOP=1
export SYNC_TENSORS_OPBYOP=1
```

And see if it is any faster.

**Comment by jinluyang** [comment]
Hi，I encountered the same problem, and found directly printing Tensors will introduce aten::_local_scalar_dense(). Just in case someone else run into similar problems.

**Comment by MaxGhi8** [comment]
Hello, I encountered an issue with the function aten:local_scalar_dense. In particular using the pytorch profiler I see that the command `coefficients[0:-1:coefficients.size(0)] *= torch.tensor(2)` increase a lot the usage of aten::local_scalr_dense, and that cause an augmentation of 1 seconds per epochs ... It is annoying because this is one of the simplest operation of the code and it takes approximately 1/8 of the total times of each epoch ... Anyone knows how to fix it?
