### ISSUE TITLE
Support for grouped convolutions?

### ISSUE THREAD

**Issue by brianhhu** [pytorch/xla#969]
Are grouped convolutions currently supported? Using the following in my model causes my training script to hang. Removing the "groups" keyword argument allows training to proceed as normal.

```Python
self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride, padding=1, groups=planes, bias=False)
```

**Comment by asuhan** [comment]
They're supported in the sense that they should work, but they go through a CPU interop mode which might be very slow and effectively look stuck. @ailzhang recently added native support for grouped convolutions I think, in which case you should be good downloading the nightly image. Can you confirm @ailzhang that this is expected to be lowered to XLA?

**Comment by dlibenzi** [comment]
Yes, @ailzhang improved the existing, partial (some of them would go to CPU - which is why it seems it is "hanging", but it is just slow), convolution support to enable full lowering to TPU via a new PyTorch entry point:

https://github.com/pytorch/xla/blob/5a84d0611f2795ddfdcbe953e8605cd2b898f78c/torch_xla/csrc/ops/convolution_overrideable.h#L12

Getting nightly Docker or wheels should get you TPU support for grouped convolutions.

**Comment by ailzhang** [comment]
Yea currently convolution should be all lowered to XLA without going back to CPU. In my sweep test I found a bug in depthwise convolution(Cin=groups and Cout %Cin =0), but it works for general grouped conv I think. I'll send a PR to fix the depthwise soon.
Let me know if it works for you in the nightly.

**Comment by brianhhu** [comment]
Ok, thanks! My use case may actually fall under the bug (i.e. a Pytorch version of EfficientNet which uses depthwise convolutions), so I'll wait for the PR.

**Comment by ailzhang** [comment]
@brianhhu Hi the fix has been merged into master, it should be available in tmr's nightly image.  It passes my local sweep test. Please feel free to give it a try and let us know if it doesn't work. Thanks!

**Comment by brianhhu** [comment]
It is working now- thanks to your hard work!
